// <auto-generated />
using System;
using CynthiasWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CynthiasWebApp.Migrations
{
    [DbContext(typeof(CynsDbContext))]
    [Migration("20220301162358_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CynthiasWebApp.ClientInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("ClientCompletedServicesId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientServiceId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompletedServicesId");

                    b.HasIndex("ClientServiceId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("ClientInfoList");
                });

            modelBuilder.Entity("CynthiasWebApp.Model.ClientCompletedServices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Receipt")
                        .HasColumnType("float");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClientCompletedServicesList");
                });

            modelBuilder.Entity("CynthiasWebApp.Model.ClientService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CheckIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClientServiceList");
                });

            modelBuilder.Entity("CynthiasWebApp.Model.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Facial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hair")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nails")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("CynthiasWebApp.ClientInfo", b =>
                {
                    b.HasOne("CynthiasWebApp.Model.ClientCompletedServices", null)
                        .WithMany("Client")
                        .HasForeignKey("ClientCompletedServicesId");

                    b.HasOne("CynthiasWebApp.Model.ClientService", null)
                        .WithMany("Client")
                        .HasForeignKey("ClientServiceId");

                    b.HasOne("CynthiasWebApp.Model.ServiceType", null)
                        .WithMany("Client")
                        .HasForeignKey("ServiceTypeId");
                });

            modelBuilder.Entity("CynthiasWebApp.Model.ClientCompletedServices", b =>
                {
                    b.Navigation("Client");
                });

            modelBuilder.Entity("CynthiasWebApp.Model.ClientService", b =>
                {
                    b.Navigation("Client");
                });

            modelBuilder.Entity("CynthiasWebApp.Model.ServiceType", b =>
                {
                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
